# Generated by Django 3.0.2 on 2020-03-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='conatct_date',
            new_name='contact_date',
        ),
    ]
